CREATE DATABASE IF NOT EXISTS catchmind_db;
CREATE DATABASE IF NOT EXISTS kkutu_db;
CREATE DATABASE IF NOT EXISTS oh_mock_db;

CREATE DATABASE IF NOT EXISTS member_db; -- 회원 정보 DB

USE member_db;
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE, -- 로그인 ID
    password VARCHAR(255) NOT NULL,
    nickname VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);